### PR TITLE
Minor fixes to replicate Kinnay's markdown files

### PR DESCRIPTION
**Pull request by DaniElectra**
- Reverse Name and Type on classes tables
- Add check for classes that have no fields.

I also want to replicate the structure inheritance message. Should I replicate the original messages or use the message from our wiki?

### CODE REVIEW

**Comment by jonbarrow** [comment]
> Should I replicate the original messages or use the message from our wiki?

That depends on whether or not you want the file produced here on Kinnay's wiki or ours. The information about structure inheritance that our wiki links to does not exist on Kinnays wiki, making it useless there

Ideally moving forward I'd like to move our tools to be integrated with our own systems, which unfortunately means likely tailoring these things to our needs. We can still provide the information itself to Kinnay, I'd like both wikis to have accurate information, but it will likely mean we won't be able to just give him generated documentation

This also means I'll likely be changing the link generation and such to work with our wiki instead

I understand if there's objections to this, but now that things are split we have to make the choice of which one we cater to directly and which one we do not

**Comment by DaniElectra** [comment]
> > Should I replicate the original messages or use the message from our wiki?
> 
> That depends on whether or not you want the file produced here on Kinnay's wiki or ours. The information about structure inheritance that our wiki links to does not exist on Kinnays wiki, making it useless there

Oh, that's right! I haven't thought of the links! I originally meant about the formatting, which is different on the wikis.

Our format:
> This structure inherits from Structure

Kinnay's format:
| This structure inherits from Structure |
| --- |

> Ideally moving forward I'd like to move our tools to be integrated with our own systems, which unfortunately means likely tailoring these things to our needs. We can still provide the information itself to Kinnay, I'd like both wikis to have accurate information, but it will likely mean we won't be able to just give him generated documentation
> 
> This also means I'll likely be changing the link generation and such to work with our wiki instead

For this case, I think I can use our formatting, but still link to Kinnay's wiki for now? I'm open to other suggestions though

> I understand if there's objections to this, but now that things are split we have to make the choice of which one we cater to directly and which one we do not

I agree. I think we should start focusing our changes against our wiki and keep compatibility with Kinnay's *if possible*.

**Comment by jonbarrow** [comment]
Oh right of course! My apolgies, I misunderstood. Yes that all sounds fine. We can't use Kinnay's format on our wiki as the markdown parser we use doesn't support tables like that (even when using GFM, for somereason), and the theme I chose has those info boxes instead which I felt was a good substitute

**Comment by DaniElectra** [comment]
Done! I also fixed the broken links to local classes by appending `-structure` at the end of the link

**Pull request merged**
